#!/bin/bash
# ============================================================
# Shell Timer - ISPConfig Integration Installer
# 
# ZERO ISPConfig files modified!
# Uses Apache mod_substitute to inject JS.
# Survives ISPConfig updates without any action needed.
#
# Usage: sudo ./install.sh [install|uninstall|status]
# ============================================================

set -euo pipefail

ISPCONFIG_WEB="/usr/local/ispconfig/interface/web"
SHELL_TIMER_DIR="${ISPCONFIG_WEB}/shell_timer"
SHELL_MANAGER_DIR="/usr/local/shell-access-manager"
APACHE_CONF="/etc/apache2/conf-available/shell-timer.conf"
SUDOERS_FILE="/etc/sudoers.d/shell-timer"
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
# Apache parses every file in sites-enabled, so vhost backups must NOT be
# written next to the original when the original lives there.
BACKUP_DIR="/var/backups/shell-timer"

RED='\e[31m'; GREEN='\e[32m'; YELLOW='\e[33m'; CYAN='\e[36m'; NC='\e[0m'
log_ok()   { echo -e "  ${GREEN}✓${NC} $*"; }
log_warn() { echo -e "  ${YELLOW}!${NC} $*"; }
log_err()  { echo -e "  ${RED}✗${NC} $*"; }
log_info() { echo -e "  ${CYAN}→${NC} $*"; }

# Back a config file up outside every directory Apache includes.
backup_config() {
    local src="$1" tag="${2:-}"
    mkdir -p "$BACKUP_DIR"
    cp "$src" "${BACKUP_DIR}/$(basename "$src").bak${tag}.$(date +%Y%m%d%H%M%S)"
}

# A *.bak file inside sites-enabled is read by Apache as a second copy of the
# vhost, which takes the whole config down with
#   "Cannot define multiple Listeners on the same IP:port".
# Earlier versions backed up in place, so clear out anything left behind.
sweep_stray_backups() {
    local dir="/etc/apache2/sites-enabled" f
    [ -d "$dir" ] || return 0
    for f in "$dir"/*.bak "$dir"/*.bak.* "$dir"/*~; do
        [ -f "$f" ] || continue
        mkdir -p "$BACKUP_DIR"
        mv "$f" "${BACKUP_DIR}/$(basename "$f")"
        log_warn "Apache által beolvasott mentés áthelyezve: $f -> $BACKUP_DIR/"
    done
    return 0
}

# Which user does the ISPConfig panel's PHP actually run as? With mod_fcgid +
# suexec (the ISPConfig default) it is NOT www-data but the vhost's
# SuexecUserGroup, normally "ispconfig". Granting sudo to the wrong user leaves
# every enable/disable failing with "sudo: a password is required".
detect_panel_user() {
    local vhost user=""
    for vhost in /etc/apache2/sites-enabled/000-ispconfig.vhost \
                 /etc/apache2/sites-available/ispconfig.vhost \
                 /etc/apache2/sites-available/ispconfig.conf; do
        [ -f "$vhost" ] || continue
        user=$(grep -oP '^[[:space:]]*SuexecUserGroup[[:space:]]+\K[^[:space:]]+' "$vhost" 2>/dev/null | head -1 || true)
        [ -n "$user" ] && break
        user=$(grep -oP '^[[:space:]]*AssignUserId[[:space:]]+\K[^[:space:]]+' "$vhost" 2>/dev/null | head -1 || true)
        [ -n "$user" ] && break
    done

    # Fall back to the owner of the panel's fcgi starter: suexec runs the CGI as
    # that user, so it is authoritative when the vhost cannot be read.
    if [ -z "$user" ] && [ -f /var/www/php-fcgi-scripts/ispconfig/.php-fcgi-starter ]; then
        user=$(stat -c %U /var/www/php-fcgi-scripts/ispconfig/.php-fcgi-starter 2>/dev/null || true)
    fi

    [ -n "$user" ] || user="ispconfig"
    id -u "$user" >/dev/null 2>&1 || user="www-data"
    echo "$user"
}

# Prove the grant works instead of trusting that the sudoers file exists.
check_sudo_for() {
    local user="$1" script="${SHELL_MANAGER_DIR}/enable-shell-user.sh"
    id -u "$user" >/dev/null 2>&1 || return 1
    if command -v runuser >/dev/null 2>&1; then
        runuser -u "$user" -- sudo -n -l "$script" >/dev/null 2>&1
    else
        su -s /bin/sh -c "sudo -n -l $(printf '%q' "$script")" "$user" >/dev/null 2>&1
    fi
}

# shell-access-manager.conf is 0600 root, so the panel process cannot read the
# limits and would silently show the built-in defaults. Publish just those two
# numbers world-readable next to the state files.
write_panel_limits() {
    local conf="${SHELL_MANAGER_DIR}/shell-access-manager.conf"
    local out="/var/lib/shell-access-manager/panel-limits.conf"
    local idle hard
    [ -f "$conf" ] || return 0
    idle=$(grep -oP '^[[:space:]]*IDLE_LIMIT=\K[0-9]+' "$conf" 2>/dev/null | tail -1 || true)
    hard=$(grep -oP '^[[:space:]]*HARD_LIMIT=\K[0-9]+' "$conf" 2>/dev/null | tail -1 || true)
    [ -n "$idle" ] || idle=10800
    [ -n "$hard" ] || hard=28800
    printf '# Generated by install.sh from %s\n# Read-only copy of the limits for the ISPConfig panel.\nIDLE_LIMIT=%s\nHARD_LIMIT=%s\n' \
        "$conf" "$idle" "$hard" > "$out"
    chmod 644 "$out"
    log_ok "Panel limitek: IDLE=${idle}s HARD=${hard}s -> $out"
    return 0
}

# ============================================================
# INSTALL
# ============================================================
do_install() {
    echo ""
    echo "╔══════════════════════════════════════════════════════╗"
    echo "║  Shell Timer - ISPConfig Integration                 ║"
    echo "║  Zero ISPConfig file modifications!                  ║"
    echo "╚══════════════════════════════════════════════════════╝"
    echo ""

    # --- Checks ---
    [ ! -d "$ISPCONFIG_WEB" ] && { log_err "ISPConfig not found: $ISPCONFIG_WEB"; exit 1; }
    [ ! -d "$SHELL_MANAGER_DIR" ] && { log_err "Shell Access Manager not found: $SHELL_MANAGER_DIR"; exit 1; }

    # --- 1. Deploy web files ---
    echo "1. Web fájlok telepítése..."
    mkdir -p "$SHELL_TIMER_DIR"
    
    local src="${SCRIPT_DIR}/shell_timer"
    [ ! -d "$src" ] && src="${SCRIPT_DIR}/../shell_timer"
    [ ! -d "$src" ] && { log_err "Source files not found"; exit 1; }

    cp "$src/api.php"       "$SHELL_TIMER_DIR/"
    cp "$src/timer.js"      "$SHELL_TIMER_DIR/"
    cp "$src/dashboard.php" "$SHELL_TIMER_DIR/"
    chown -R ispconfig:ispconfig "$SHELL_TIMER_DIR"
    chmod 755 "$SHELL_TIMER_DIR"
    chmod 644 "$SHELL_TIMER_DIR"/*
    log_ok "Fájlok: $SHELL_TIMER_DIR/"

    # --- 2. Apache mod_substitute ---
    echo ""
    echo "2. Apache konfiguráció..."
    
    # Enable mod_substitute if not already
    if ! apache2ctl -M 2>/dev/null | grep -q substitute; then
        a2enmod substitute >/dev/null 2>&1
        log_ok "Apache mod_substitute engedélyezve"
    else
        log_ok "Apache mod_substitute már aktív"
    fi

    # Create Apache config that injects timer.js via the ISPConfig vhost
    # We use conf-available which is a standard Apache include dir
    cat > "$APACHE_CONF" << 'APACHECONF'
# Shell Timer - ISPConfig Integration
# Injects timer.js into ISPConfig panel pages
# This file is NOT touched by ISPConfig updates.
#
# How it works:
#   mod_substitute replaces </head> with <script>+</head>
#   in HTML responses served on port 8080 (ISPConfig panel).

<IfModule mod_substitute.c>
    # Only apply to ISPConfig panel (port 8080)
    # Applied via ISPConfig vhost - see below
</IfModule>
APACHECONF
    log_ok "Apache config: $APACHE_CONF"

    # Inject into ISPConfig vhost (port 8080)
    local VHOST="/etc/apache2/sites-available/ispconfig.vhost"
    local VHOST_CONF=""
    
    # Find the actual ISPConfig vhost file
    if [ -f "$VHOST" ]; then
        VHOST_CONF="$VHOST"
    elif [ -f "/etc/apache2/sites-available/ispconfig.conf" ]; then
        VHOST_CONF="/etc/apache2/sites-available/ispconfig.conf"
    elif [ -f "/etc/apache2/sites-enabled/000-ispconfig.vhost" ]; then
        VHOST_CONF="/etc/apache2/sites-enabled/000-ispconfig.vhost"
    fi

    if [ -n "$VHOST_CONF" ]; then
        if grep -q "shell-timer-integration" "$VHOST_CONF" 2>/dev/null; then
            log_ok "ISPConfig vhost már konfigurálva"
        else
            # Backup (never beside the original: it may live in sites-enabled)
            backup_config "$VHOST_CONF"
            
            # Insert mod_substitute directive before </VirtualHost>
            # SetEnv no-gzip 1 + INFLATE;SUBSTITUTE;DEFLATE chain: ezek nélkül
            # az ISPConfig panel gzip-pelt HTML-jén a Substitute nem hat.
            sed -i '/<\/VirtualHost>/i \
\
    # --- Shell Timer Integration (do not remove) ---\
    # shell-timer-integration\
    SetEnv no-gzip 1\
    <IfModule mod_substitute.c>\
        AddOutputFilterByType INFLATE;SUBSTITUTE;DEFLATE text/html\
        Substitute "s|</head>|<script src=\\x27/shell_timer/timer.js?v=2\\x27 defer></script></head>|ni"\
    </IfModule>' "$VHOST_CONF"
            
            log_ok "ISPConfig vhost frissítve: $VHOST_CONF"
        fi
    else
        log_warn "ISPConfig vhost nem található!"
        log_warn "Add hozzá manuálisan a </VirtualHost> elé:"
        echo ""
        echo '    <IfModule mod_substitute.c>'
        echo '        AddOutputFilterByType SUBSTITUTE text/html'
        echo "        Substitute \"s|</head>|<script src='/shell_timer/timer.js?v=1' defer></script></head>|ni\""
        echo '    </IfModule>'
        echo ""
    fi

    # --- 3. Sudoers ---
    echo ""
    echo "3. Jogosultságok beállítása..."
    local panel_user done_users=""
    panel_user=$(detect_panel_user)
    log_info "A panel PHP-ja ezen a néven fut: $panel_user"

    rm -f "$SUDOERS_FILE"
    {
        echo "# Shell Timer - ISPConfig Integration"
        echo "# Allow the ISPConfig panel process to manage shell access."
        echo "# With mod_fcgid + suexec the panel runs as the vhost's SuexecUserGroup"
        echo "# (normally ispconfig), not as www-data, so both are listed."
        for u in "$panel_user" www-data; do
            id -u "$u" >/dev/null 2>&1 || continue
            case " $done_users " in *" $u "*) continue ;; esac
            done_users="$done_users $u"
            echo "$u ALL=(root) NOPASSWD: ${SHELL_MANAGER_DIR}/enable-shell-user.sh"
            echo "$u ALL=(root) NOPASSWD: ${SHELL_MANAGER_DIR}/disable-shell-user.sh"
            echo "$u ALL=(root) NOPASSWD: ${SHELL_MANAGER_DIR}/status.sh"
        done
    } > "$SUDOERS_FILE"
    chmod 440 "$SUDOERS_FILE"
    
    if visudo -c -f "$SUDOERS_FILE" &>/dev/null; then
        log_ok "Sudoers: $SUDOERS_FILE"
    else
        log_err "Sudoers szintaxis hiba!"
        rm -f "$SUDOERS_FILE"
        exit 1
    fi

    # An existing sudoers file proves nothing: the previous version granted
    # www-data while the panel actually runs as ispconfig, so every action
    # failed with "sudo: a password is required". Verify for real.
    if check_sudo_for "$panel_user"; then
        log_ok "sudo próba sikeres: $panel_user jelszó nélkül futtathatja a szkripteket"
    else
        log_err "sudo próba SIKERTELEN: $panel_user nem tudja jelszó nélkül futtatni a szkripteket!"
        log_err "A panelről az indítás és a letiltás így nem működne."
        exit 1
    fi

    # --- 4. State dir permissions ---
    echo ""
    echo "4. Jogosultságok ellenőrzése..."
    local state_dir="/var/lib/shell-access-manager"
    if [ -d "$state_dir" ]; then
        chmod 755 "$state_dir"
        chmod 644 "$state_dir"/* 2>/dev/null || true
        log_ok "State dir olvasható: $state_dir"
    fi
    write_panel_limits
    sweep_stray_backups

    # --- 5. Restart Apache ---
    echo ""
    echo "5. Apache újraindítása..."
    if apache2ctl configtest 2>&1 | grep -q "Syntax OK"; then
        systemctl reload apache2
        log_ok "Apache újraindítva"
    else
        log_err "Apache config hiba! Ellenőrizd: apache2ctl configtest"
        exit 1
    fi

    # --- Done ---
    echo ""
    echo "╔══════════════════════════════════════════════════════╗"
    echo "║  ✅ Telepítés kész!                                  ║"
    echo "╠══════════════════════════════════════════════════════╣"
    echo "║                                                      ║"
    echo "║  Nyisd meg: https://srv.knh.hu:8080                  ║"
    echo "║  Sites → SSH-User → bármelyik user                   ║"
    echo "║  → Timer panel automatikusan megjelenik!              ║"
    echo "║                                                      ║"
    echo "║  Dashboard: Sites menüben → 'Shell Timer' link       ║"
    echo "║                                                      ║"
    echo "║  ⭐ ISPConfig frissítés után:                         ║"
    echo "║     SEMMI TEENDŐ! Minden automatikusan működik.      ║"
    echo "║                                                      ║"
    echo "║  Módosított ISPConfig fájlok: NULLA                  ║"
    echo "║  Csak a vhost-ba került 1 Apache direktíva.          ║"
    echo "╚══════════════════════════════════════════════════════╝"
    echo ""
    
    do_status
}

# ============================================================
# UNINSTALL
# ============================================================
do_uninstall() {
    echo ""
    echo "Shell Timer eltávolítása..."
    echo ""

    # --- Disable & remove watchdog (must be BEFORE removing files,
    #     otherwise the watchdog races us and re-installs them) ---
    for unit in shell-timer-watchdog.path shell-timer-watchdog.timer shell-timer-watchdog.service; do
        if systemctl list-unit-files "$unit" 2>/dev/null | grep -q "$unit"; then
            systemctl disable --now "$unit" >/dev/null 2>&1 || true
        fi
    done
    rm -f /etc/systemd/system/shell-timer-watchdog.path \
          /etc/systemd/system/shell-timer-watchdog.service \
          /etc/systemd/system/shell-timer-watchdog.timer
    systemctl daemon-reload 2>/dev/null || true
    rm -f /usr/local/shell-access-manager/ispconfig-redeploy.sh
    rm -rf /usr/local/shell-access-manager/ispconfig-templates
    log_ok "Watchdog eltávolítva (systemd units + templates)"

    # Remove web files
    if [ -d "$SHELL_TIMER_DIR" ]; then
        rm -rf "$SHELL_TIMER_DIR"
        log_ok "Eltávolítva: $SHELL_TIMER_DIR"
    fi

    # Remove Apache config
    if [ -f "$APACHE_CONF" ]; then
        rm -f "$APACHE_CONF"
        log_ok "Eltávolítva: $APACHE_CONF"
    fi

    # Remove from ISPConfig vhost
    for vhost in /etc/apache2/sites-available/ispconfig.vhost /etc/apache2/sites-available/ispconfig.conf; do
        if [ -f "$vhost" ]; then
            # Backup, then strip every known shell-timer leftover (legacy v1, v2 Include, marker)
            backup_config "$vhost" ".uninstall"
            sed -i '/Shell Timer Integration/,/<\/IfModule>/d' "$vhost"
            sed -i '\|Include conf-available/shell-timer\.conf|d' "$vhost"
            sed -i '/shell-timer-integration/d' "$vhost"
            # Clean up consecutive empty lines
            sed -i '/^$/N;/^\n$/d' "$vhost"
            log_ok "Vhost megtisztítva: $vhost"
        fi
    done

    # Remove sudoers
    if [ -f "$SUDOERS_FILE" ]; then
        rm -f "$SUDOERS_FILE"
        log_ok "Eltávolítva: $SUDOERS_FILE"
    fi

    # Reload Apache
    if apache2ctl configtest 2>&1 | grep -q "Syntax OK"; then
        systemctl reload apache2
        log_ok "Apache újratöltve"
    fi

    echo ""
    log_ok "Eltávolítás kész!"
    echo ""
}

# ============================================================
# STATUS
# ============================================================
do_status() {
    echo ""
    echo "  Shell Timer - Állapot"
    echo "  ====================="
    echo ""
    
    echo "  Fájlok:"
    for f in "$SHELL_TIMER_DIR/api.php" "$SHELL_TIMER_DIR/timer.js" "$SHELL_TIMER_DIR/dashboard.php"; do
        [ -f "$f" ] && log_ok "$f" || log_err "$f"
    done
    [ -f "$SUDOERS_FILE" ] && log_ok "$SUDOERS_FILE" || log_err "$SUDOERS_FILE"
    local panel_user
    panel_user=$(detect_panel_user)
    log_info "Panel felhasználó: $panel_user"
    if check_sudo_for "$panel_user"; then
        log_ok "sudo jogosultság él: $panel_user (jelszó nélkül)"
    else
        log_err "sudo jogosultság HIÁNYZIK: $panel_user - a panelről nem indítható a shell"
        log_info "Javítás: sudo bash $0 install"
    fi

    echo ""
    echo "  Apache:"
    if apache2ctl -M 2>/dev/null | grep -q substitute; then
        log_ok "mod_substitute aktív"
    else
        log_err "mod_substitute NEM aktív"
    fi
    
    local found_vhost=""
    for vhost in /etc/apache2/sites-available/ispconfig.vhost /etc/apache2/sites-available/ispconfig.conf; do
        if [ -f "$vhost" ] && grep -q "shell-timer-integration" "$vhost" 2>/dev/null; then
            log_ok "Vhost injection: $vhost"
            found_vhost="1"
        fi
    done
    [ -z "$found_vhost" ] && log_err "Vhost injection: NINCS"

    echo ""
    echo "  Shell Access Manager:"
    [ -d "$SHELL_MANAGER_DIR" ] && log_ok "$SHELL_MANAGER_DIR" || log_err "$SHELL_MANAGER_DIR"
    [ -d "/var/lib/shell-access-manager" ] && log_ok "State dir létezik" || log_err "State dir hiányzik"
    
    local active_count=$(ls /var/lib/shell-access-manager/*.enabled 2>/dev/null | wc -l)
    log_info "Aktív timer: ${active_count} db"
    
    echo ""
}

# ============================================================
# Main
# ============================================================
case "${1:-install}" in
    install)   do_install ;;
    uninstall) do_uninstall ;;
    status)    do_status ;;
    *)
        echo "Használat: $0 [install|uninstall|status]"
        echo ""
        echo "  install    Telepítés (ISPConfig fájlokat NEM módosít)"
        echo "  uninstall  Eltávolítás"
        echo "  status     Állapot ellenőrzés"
        exit 1
        ;;
esac
